# GitHub Actions for genCMPClient
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Siemens AG, 2021-2023

name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-make
        run: |
          # needs access to azure.archive.ubuntu.com:
          sudo apt-get update
          sudo apt-get install -y libssl-dev build-essential
          make
          make clean
          make build_no_tls

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: doc
        run: |
          # needs access to azure.archive.ubuntu.com:
          sudo apt-get update
          sudo apt-get install -y libpod-markdown-perl doxygen
          make doc

  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deb
        run: |
          # needs access to azure.archive.ubuntu.com:
          sudo apt-get update
          sudo apt-get install -y libssl-dev devscripts # needed? debhelper pkg-config
          make deb
