# GitHub Actions for genCMPClient
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Siemens AG, 2021-2023

name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-make
        run: |
          # sudo apt-get update # disabled due to Unable to connect to azure.archive.ubuntu.com
          sudo apt-get install -y libssl-dev build-essential
          make
          make clean
          make build_no_tls

  deb-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deb-doc
        run: |
          # sudo apt-get update # disabled due to Unable to connect to azure.archive.ubuntu.com
          sudo apt-get install -y libpod-markdown-perl || true
          make doc
          sudo apt-get install -y libssl-dev devscripts debhelper pkg-config
          make deb
